spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/manchkin
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true
